create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  name text not null default 'Usuario',
  bio text not null default 'Aprendiendo programación con EduCode',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.modules (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  icon text not null default 'pi pi-book',
  accent text not null default '#10b981',
  icon_bg text not null default 'rgba(16, 185, 129, 0.1)',
  difficulty text not null default 'Principiante',
  sort_order int not null unique
);

create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  module_id bigint not null references public.modules(id) on delete cascade,
  title text not null,
  duration text not null default '10 min',
  sort_order int not null,
  content jsonb not null default '[]'::jsonb,
  unique (module_id, sort_order)
);

create table if not exists public.user_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  module_id bigint not null references public.modules(id) on delete cascade,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  completed_at timestamptz not null default now(),
  primary key (user_id, lesson_id)
);

create table if not exists public.user_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  dark_mode boolean not null default false,
  language text not null default 'es',
  email_notifications boolean not null default true,
  reminder_notifications boolean not null default true,
  achievement_notifications boolean not null default true,
  updated_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at
before update on public.profiles
for each row execute function public.touch_updated_at();

drop trigger if exists user_settings_touch_updated_at on public.user_settings;
create trigger user_settings_touch_updated_at
before update on public.user_settings
for each row execute function public.touch_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'name', 'Usuario')
  )
  on conflict (id) do nothing;

  insert into public.user_settings (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.modules enable row level security;
alter table public.lessons enable row level security;
alter table public.user_progress enable row level security;
alter table public.user_settings enable row level security;

drop policy if exists "profiles select own" on public.profiles;
create policy "profiles select own"
on public.profiles for select
using (auth.uid() = id);

drop policy if exists "profiles update own" on public.profiles;
create policy "profiles update own"
on public.profiles for update
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "profiles insert own" on public.profiles;
create policy "profiles insert own"
on public.profiles for insert
with check (auth.uid() = id);

drop policy if exists "modules public read" on public.modules;
create policy "modules public read"
on public.modules for select
using (true);

drop policy if exists "lessons public read" on public.lessons;
create policy "lessons public read"
on public.lessons for select
using (true);

drop policy if exists "progress select own" on public.user_progress;
create policy "progress select own"
on public.user_progress for select
using (auth.uid() = user_id);

drop policy if exists "progress insert own" on public.user_progress;
create policy "progress insert own"
on public.user_progress for insert
with check (auth.uid() = user_id);

drop policy if exists "progress update own" on public.user_progress;
create policy "progress update own"
on public.user_progress for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "progress delete own" on public.user_progress;
create policy "progress delete own"
on public.user_progress for delete
using (auth.uid() = user_id);

drop policy if exists "settings select own" on public.user_settings;
create policy "settings select own"
on public.user_settings for select
using (auth.uid() = user_id);

drop policy if exists "settings insert own" on public.user_settings;
create policy "settings insert own"
on public.user_settings for insert
with check (auth.uid() = user_id);

drop policy if exists "settings update own" on public.user_settings;
create policy "settings update own"
on public.user_settings for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

insert into public.modules (id, title, description, icon, accent, icon_bg, difficulty, sort_order)
values
  (1, 'Introducción a Python', 'Conoce los fundamentos de la programación con Python desde cero.', 'pi pi-python', '#10b981', 'rgba(16, 185, 129, 0.1)', 'Principiante', 1),
  (2, 'Variables', 'Aprende a almacenar y manipular información en tus programas.', 'pi pi-database', '#3b82f6', 'rgba(59, 130, 246, 0.1)', 'Principiante', 2),
  (3, 'Tipos de datos', 'Descubre cómo Python maneja textos, números y valores booleanos.', 'pi pi-table', '#8b5cf6', 'rgba(139, 92, 246, 0.1)', 'Principiante', 3),
  (4, 'Operadores', 'Domina las operaciones aritméticas, lógica y comparación.', 'pi pi-calculator', '#f59e0b', 'rgba(245, 158, 11, 0.1)', 'Principiante', 4),
  (5, 'Condicionales', 'Controla el flujo de tu programa con if, else y elif.', 'pi pi-sitemap', '#ef4444', 'rgba(239, 68, 68, 0.1)', 'Intermedio', 5),
  (6, 'Bucles', 'Automatiza tareas repetitivas con for y while.', 'pi pi-reload', '#06b6d4', 'rgba(6, 182, 212, 0.1)', 'Intermedio', 6)
on conflict (id) do update set
  title = excluded.title,
  description = excluded.description,
  icon = excluded.icon,
  accent = excluded.accent,
  icon_bg = excluded.icon_bg,
  difficulty = excluded.difficulty,
  sort_order = excluded.sort_order;

insert into public.lessons (module_id, title, duration, sort_order, content)
values
  (1, '¿Qué es Python?', '10 min', 1, '[{"type":"text","value":"Python es un lenguaje de programación interpretado, de alto nivel y multiplataforma."},{"type":"code","value":"print(\"Hola, mundo!\")"}]'),
  (1, 'Instalación y configuración', '15 min', 2, '[{"type":"text","value":"Puedes instalar Python desde python.org o practicar en entornos online."},{"type":"code","value":"python --version"}]'),
  (1, 'Tu primer programa', '12 min', 3, '[{"type":"text","value":"El primer programa clásico muestra un mensaje en pantalla."},{"type":"code","value":"print(\"Bienvenido a EduCode\")"}]'),
  (1, 'Comentarios y buenas prácticas', '8 min', 4, '[{"type":"text","value":"Los comentarios explican decisiones importantes del código."},{"type":"code","value":"# Esto es un comentario\\nprint(\"El código sigue funcionando\")"}]'),
  (1, 'Ejercicios prácticos', '20 min', 5, '[{"type":"text","value":"Escribe un programa que imprima tu nombre."},{"type":"code","value":"print(\"Tu nombre aquí\")"}]'),
  (2, '¿Qué son las variables?', '10 min', 1, '[{"type":"text","value":"Una variable guarda información con un nombre."},{"type":"code","value":"nombre = \"Ana\"\\nedad = 25"}]'),
  (2, 'Tipos de variables', '12 min', 2, '[{"type":"text","value":"Python tiene tipos como int, float, str y bool."},{"type":"code","value":"activo = True\\nprecio = 19.99"}]'),
  (2, 'Asignación y reasignación', '10 min', 3, '[{"type":"text","value":"Puedes cambiar el valor de una variable."},{"type":"code","value":"contador = 0\\ncontador = contador + 1"}]'),
  (2, 'Ejercicios prácticos', '20 min', 4, '[{"type":"text","value":"Crea variables con tu nombre y edad, luego imprímelas."}]'),
  (3, 'Números enteros y flotantes', '10 min', 1, '[{"type":"text","value":"Python permite operar con enteros y decimales."},{"type":"code","value":"print(10 / 3)\\nprint(10 // 3)"}]'),
  (3, 'Cadenas de texto', '12 min', 2, '[{"type":"text","value":"Las cadenas representan texto."},{"type":"code","value":"nombre = \"Ana\"\\nprint(f\"Hola, {nombre}\")"}]'),
  (3, 'Booleanos', '8 min', 3, '[{"type":"text","value":"Los booleanos solo pueden ser True o False."}]'),
  (3, 'Ejercicios prácticos', '20 min', 4, '[{"type":"text","value":"Calcula el área de un círculo con radio 5."}]'),
  (4, 'Operadores aritméticos', '10 min', 1, '[{"type":"text","value":"Permiten sumar, restar, multiplicar y dividir."},{"type":"code","value":"print(10 + 5)"}]'),
  (4, 'Operadores de comparación', '10 min', 2, '[{"type":"text","value":"Comparan valores y devuelven booleanos."},{"type":"code","value":"print(5 == 5)"}]'),
  (4, 'Operadores lógicos', '10 min', 3, '[{"type":"text","value":"Combinan condiciones con and, or y not."}]'),
  (5, 'Sentencia if', '12 min', 1, '[{"type":"text","value":"if ejecuta un bloque si una condición es verdadera."}]'),
  (5, 'Else y elif', '12 min', 2, '[{"type":"text","value":"else y elif permiten manejar rutas alternativas."}]'),
  (5, 'Condiciones anidadas', '15 min', 3, '[{"type":"text","value":"Puedes colocar una condición dentro de otra."}]'),
  (5, 'Operador ternario', '10 min', 4, '[{"type":"text","value":"Permite expresar una decisión simple en una línea."}]'),
  (5, 'Ejercicios prácticos', '25 min', 5, '[{"type":"text","value":"Determina si un número es positivo, negativo o cero."}]'),
  (6, 'Bucle for', '12 min', 1, '[{"type":"text","value":"for recorre una secuencia."},{"type":"code","value":"for i in range(5):\\n    print(i)"}]'),
  (6, 'Bucle while', '12 min', 2, '[{"type":"text","value":"while ejecuta mientras una condición sea verdadera."}]'),
  (6, 'Break y continue', '10 min', 3, '[{"type":"text","value":"break sale del bucle y continue salta una vuelta."}]'),
  (6, 'Ejercicios prácticos', '25 min', 4, '[{"type":"text","value":"Imprime los números pares del 1 al 20."}]')
on conflict (module_id, sort_order) do update set
  title = excluded.title,
  duration = excluded.duration,
  content = excluded.content;

select setval(pg_get_serial_sequence('public.modules', 'id'), (select max(id) from public.modules));
select setval(pg_get_serial_sequence('public.lessons', 'id'), (select max(id) from public.lessons));
